service: rusty-photography

plugins:
  - serverless-rust

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  runtime: rust

package:
  individually: true

functions:
  hello:
    handler: photography.hello

  web:
    handler: photography.web
    events:
      - http:
          path: /
          method: any
      - http:
          path: "{proxy+}"
          method: any