service: rusty-photography

plugins:
  - serverless-rust

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  runtime: rust

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Scan"
      Resource:
        Fn::Join:
          - ':'
          - - "arn:aws:dynamodb"
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - "table/photography-prod-photograph"

package:
  individually: true

functions:
  hello:
    handler: photography.hello

  web:
    handler: photography.web
    events:
      - http:
          path: /
          method: any
      - http:
          path: "{proxy+}"
          method: any